### ISSUE TITLE
a space after inline markup makes it - and content that follows - disappear

### ISSUE THREAD

**Issue by mgielda** [seikichi/restructured#3]
Hi @seikichi - first of all, awesome work and thanks for your effort! I have stumbled upon one problem while playing with the parser and decided to report it:

```
**test** 
test
```

results in nothing (tested in the live demo after downloading github master).

I assume it's a minor bug and not critical, but just wanted you to know.

**Comment by seikichi** [comment]
Hi @mgielda, I'm glad to receive your comment.

Did you try online demo page ([link](https://seikichi.github.io/restructured/))? If so, that bug is fixed in current `restructured` version (0.1.11):

``` sh
$ npm install -g restrutured
$ cat <<EOF | restructured
pipe heredoc% **hoge** 
pipe heredoc% hoge
pipe heredoc% EOF
{"type":"document","children":[{"type":"paragraph","children":[{"type":"strong","children":[{"type":"text","value":"hoge"}]},{"type":"text","value":"\n"},{"type":"text","value":"hoge\n"}]}]}
```

But I forgot to update the online demo page ;-p. Thank you for bug reporting! I'll fix ASAP.

**Comment by mgielda** [comment]
Hi @seikichi, OK! I downloaded the code but did use the example, which is same as the online demo, so I think that is why. Thanks for a quick reaction!

**Comment by seikichi** [comment]
Hi @mgielda 

I fixed the bug and updated [examples directory](https://github.com/seikichi/restructured/commit/267934aa7a24a1bcb25c9c0cfd53e403589a1af2) and [demo site](https://seikichi.github.io/restructured/).

Sorry for late fix, I was sick last week 😨
